name: fitfood
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^7.3.0
  flutter_html: ^3.0.0-beta.2  # Uncomment if needed
  hive: 
  hive_flutter: 
  path_provider: ^2.0.5
  share: ^2.0.4
  url_launcher: ^6.0.12
  
  bottom_nav_bar:
    git:
      url: https://github.com/Ansh-Rathod/bottom_nav_bar
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  dio_log: ^2.0.0
  equatable: ^2.0.3
  firebase_dynamic_links: ^5.4.8 
  step_progress_indicator: ^1.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2 
  cloud_firestore: ^4.14.0
  elastic_client: ^0.3.9
  http: ^0.13.4
  another_flushbar: ^1.10.28
  shared_preferences: ^2.0.13
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.8.13
  device_info_plus: ^3.2.2
  flutter_progress_hud: ^2.0.0
  animations: ^2.0.2
  persistent_bottom_nav_bar: ^4.0.2
  pay: ^1.1.2
  get: ^4.6.1
  connectivity_plus: ^2.3.0
  flutter_local_notifications: ^9.5.3+1
  flutter_charts: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: 
  build_runner: 
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/splashscreen/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Medium.ttf
    - family: Telma
      fonts:
        - asset: fonts/Telma-Medium.ttf
